scan_filter_chain:
- type: LaserArrayFilter
  name: laser_median_filter
  params: 
    range_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 5
          unused: 10
    intensity_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 5
          unused: 10
- name: range
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.3
    upper_threshold: 4
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 20
    window: 1
